name: geocode
version: 1.0.0
homepage: https://github.com/imvalient/geocode
repository: https://github.com/imvalient/geocode
description: >-
    Package to make Geocode requests. It exposes two methods to translate
    coordinates into locations and addresses into coordinates.

environment:
    sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http: ^0.13.1
dev_dependencies:
  test: ^1.16.8