name: geocode
version: 0.1.2
homepage: https://github.com/imvalient/geocode
repository: https://github.com/imvalient/geocode
description: >-
    Package to make Geocode requests. It exposes two methods to translate
    coordinates into locations and addresses into coordinates.

environment:
    sdk: ">=2.3.0 <3.0.0"

dependencies:
    http: ^0.12.2

dev_dependencies:
    test: ^1.15.7